application: brain-of
version: 3
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.3"
- name: markupsafe
  version: "latest"
- name: lxml
  version: "latest"

builtins:
- django_wsgi: on

handlers:
- url: /assets
  static_dir: assets
